networks:
  beacon-dev:
    external: true

services:
  beacon-analysis-server:
    container_name: beacon-analysis-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ../.kaggle:/workspace/.kaggle:ro
      - vscode-extension:/root/.vscode-server-insiders
    command: sleep infinity
    networks:
      - beacon-dev

volumes:
  vscode-extension: